// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class RuntimeFlagsMessage {
  RuntimeFlagsMessage({
    this.wakeLockEnabled,
    this.networkHeartbeatEnabled,
    this.networkHeartbeatIntervalSeconds,
    this.performanceMode,
    this.memoryLimitEnabled,
  });

  bool? wakeLockEnabled;

  bool? networkHeartbeatEnabled;

  int? networkHeartbeatIntervalSeconds;

  String? performanceMode;

  bool? memoryLimitEnabled;

  List<Object?> _toList() {
    return <Object?>[
      wakeLockEnabled,
      networkHeartbeatEnabled,
      networkHeartbeatIntervalSeconds,
      performanceMode,
      memoryLimitEnabled,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RuntimeFlagsMessage decode(Object result) {
    result as List<Object?>;
    return RuntimeFlagsMessage(
      wakeLockEnabled: result[0] as bool?,
      networkHeartbeatEnabled: result[1] as bool?,
      networkHeartbeatIntervalSeconds: result[2] as int?,
      performanceMode: result[3] as String?,
      memoryLimitEnabled: result[4] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RuntimeFlagsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(wakeLockEnabled, other.wakeLockEnabled) &&
        _deepEquals(networkHeartbeatEnabled, other.networkHeartbeatEnabled) &&
        _deepEquals(
          networkHeartbeatIntervalSeconds,
          other.networkHeartbeatIntervalSeconds,
        ) &&
        _deepEquals(performanceMode, other.performanceMode) &&
        _deepEquals(memoryLimitEnabled, other.memoryLimitEnabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NetworkInterfaceStateMessage {
  NetworkInterfaceStateMessage({
    required this.available,
    this.interfaceName,
    required this.interfaceIndex,
    required this.generation,
    this.reason,
    required this.updatedAtMillis,
  });

  bool available;

  String? interfaceName;

  int interfaceIndex;

  int generation;

  String? reason;

  int updatedAtMillis;

  List<Object?> _toList() {
    return <Object?>[
      available,
      interfaceName,
      interfaceIndex,
      generation,
      reason,
      updatedAtMillis,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NetworkInterfaceStateMessage decode(Object result) {
    result as List<Object?>;
    return NetworkInterfaceStateMessage(
      available: result[0]! as bool,
      interfaceName: result[1] as String?,
      interfaceIndex: result[2]! as int,
      generation: result[3]! as int,
      reason: result[4] as String?,
      updatedAtMillis: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NetworkInterfaceStateMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(available, other.available) &&
        _deepEquals(interfaceName, other.interfaceName) &&
        _deepEquals(interfaceIndex, other.interfaceIndex) &&
        _deepEquals(generation, other.generation) &&
        _deepEquals(reason, other.reason) &&
        _deepEquals(updatedAtMillis, other.updatedAtMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class UrlTestRequestMessage {
  UrlTestRequestMessage({
    required this.groupTag,
    required this.targetOutboundTag,
    required this.priorityOutboundTag,
    required this.excludeOutboundTag,
    required this.url,
    required this.timeoutMillis,
    required this.concurrency,
    required this.deadlineMillis,
    required this.force,
  });

  String groupTag;

  String targetOutboundTag;

  String priorityOutboundTag;

  String excludeOutboundTag;

  String url;

  int timeoutMillis;

  int concurrency;

  int deadlineMillis;

  bool force;

  List<Object?> _toList() {
    return <Object?>[
      groupTag,
      targetOutboundTag,
      priorityOutboundTag,
      excludeOutboundTag,
      url,
      timeoutMillis,
      concurrency,
      deadlineMillis,
      force,
    ];
  }

  Object encode() {
    return _toList();
  }

  static UrlTestRequestMessage decode(Object result) {
    result as List<Object?>;
    return UrlTestRequestMessage(
      groupTag: result[0]! as String,
      targetOutboundTag: result[1]! as String,
      priorityOutboundTag: result[2]! as String,
      excludeOutboundTag: result[3]! as String,
      url: result[4]! as String,
      timeoutMillis: result[5]! as int,
      concurrency: result[6]! as int,
      deadlineMillis: result[7]! as int,
      force: result[8]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UrlTestRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(groupTag, other.groupTag) &&
        _deepEquals(targetOutboundTag, other.targetOutboundTag) &&
        _deepEquals(priorityOutboundTag, other.priorityOutboundTag) &&
        _deepEquals(excludeOutboundTag, other.excludeOutboundTag) &&
        _deepEquals(url, other.url) &&
        _deepEquals(timeoutMillis, other.timeoutMillis) &&
        _deepEquals(concurrency, other.concurrency) &&
        _deepEquals(deadlineMillis, other.deadlineMillis) &&
        _deepEquals(force, other.force);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class PreconnectUrlTestRequestMessage {
  PreconnectUrlTestRequestMessage({
    required this.config,
    required this.groupTag,
    required this.targetOutboundTag,
    required this.url,
    required this.timeoutMillis,
    required this.deadlineMillis,
  });

  String config;

  String groupTag;

  String targetOutboundTag;

  String url;

  int timeoutMillis;

  int deadlineMillis;

  List<Object?> _toList() {
    return <Object?>[
      config,
      groupTag,
      targetOutboundTag,
      url,
      timeoutMillis,
      deadlineMillis,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PreconnectUrlTestRequestMessage decode(Object result) {
    result as List<Object?>;
    return PreconnectUrlTestRequestMessage(
      config: result[0]! as String,
      groupTag: result[1]! as String,
      targetOutboundTag: result[2]! as String,
      url: result[3]! as String,
      timeoutMillis: result[4]! as int,
      deadlineMillis: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PreconnectUrlTestRequestMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(config, other.config) &&
        _deepEquals(groupTag, other.groupTag) &&
        _deepEquals(targetOutboundTag, other.targetOutboundTag) &&
        _deepEquals(url, other.url) &&
        _deepEquals(timeoutMillis, other.timeoutMillis) &&
        _deepEquals(deadlineMillis, other.deadlineMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class PreconnectUrlTestResultMessage {
  PreconnectUrlTestResultMessage({
    required this.tag,
    required this.delayMillis,
    required this.timeSeconds,
    required this.status,
    required this.error,
    required this.errorCode,
  });

  String tag;

  int delayMillis;

  int timeSeconds;

  String status;

  String error;

  String errorCode;

  List<Object?> _toList() {
    return <Object?>[tag, delayMillis, timeSeconds, status, error, errorCode];
  }

  Object encode() {
    return _toList();
  }

  static PreconnectUrlTestResultMessage decode(Object result) {
    result as List<Object?>;
    return PreconnectUrlTestResultMessage(
      tag: result[0]! as String,
      delayMillis: result[1]! as int,
      timeSeconds: result[2]! as int,
      status: result[3]! as String,
      error: result[4]! as String,
      errorCode: result[5]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PreconnectUrlTestResultMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(tag, other.tag) &&
        _deepEquals(delayMillis, other.delayMillis) &&
        _deepEquals(timeSeconds, other.timeSeconds) &&
        _deepEquals(status, other.status) &&
        _deepEquals(error, other.error) &&
        _deepEquals(errorCode, other.errorCode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class CoreBundleSlotMessage {
  CoreBundleSlotMessage({
    required this.releaseSequence,
    required this.version,
    required this.abi,
    required this.sha256,
  });

  int releaseSequence;

  String version;

  String abi;

  String sha256;

  List<Object?> _toList() {
    return <Object?>[releaseSequence, version, abi, sha256];
  }

  Object encode() {
    return _toList();
  }

  static CoreBundleSlotMessage decode(Object result) {
    result as List<Object?>;
    return CoreBundleSlotMessage(
      releaseSequence: result[0]! as int,
      version: result[1]! as String,
      abi: result[2]! as String,
      sha256: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CoreBundleSlotMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(releaseSequence, other.releaseSequence) &&
        _deepEquals(version, other.version) &&
        _deepEquals(abi, other.abi) &&
        _deepEquals(sha256, other.sha256);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class CoreManagerStateMessage {
  CoreManagerStateMessage({
    required this.embeddedVersion,
    this.active,
    this.previous,
    this.candidate,
    required this.trustedKeyRingAvailable,
    required this.usingEmbeddedFallback,
    required this.runtimeDisconnected,
    required this.recoveryRollbackAllowed,
  });

  String embeddedVersion;

  CoreBundleSlotMessage? active;

  CoreBundleSlotMessage? previous;

  CoreBundleSlotMessage? candidate;

  bool trustedKeyRingAvailable;

  bool usingEmbeddedFallback;

  bool runtimeDisconnected;

  bool recoveryRollbackAllowed;

  List<Object?> _toList() {
    return <Object?>[
      embeddedVersion,
      active,
      previous,
      candidate,
      trustedKeyRingAvailable,
      usingEmbeddedFallback,
      runtimeDisconnected,
      recoveryRollbackAllowed,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CoreManagerStateMessage decode(Object result) {
    result as List<Object?>;
    return CoreManagerStateMessage(
      embeddedVersion: result[0]! as String,
      active: result[1] as CoreBundleSlotMessage?,
      previous: result[2] as CoreBundleSlotMessage?,
      candidate: result[3] as CoreBundleSlotMessage?,
      trustedKeyRingAvailable: result[4]! as bool,
      usingEmbeddedFallback: result[5]! as bool,
      runtimeDisconnected: result[6]! as bool,
      recoveryRollbackAllowed: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CoreManagerStateMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(embeddedVersion, other.embeddedVersion) &&
        _deepEquals(active, other.active) &&
        _deepEquals(previous, other.previous) &&
        _deepEquals(candidate, other.candidate) &&
        _deepEquals(trustedKeyRingAvailable, other.trustedKeyRingAvailable) &&
        _deepEquals(usingEmbeddedFallback, other.usingEmbeddedFallback) &&
        _deepEquals(runtimeDisconnected, other.runtimeDisconnected) &&
        _deepEquals(recoveryRollbackAllowed, other.recoveryRollbackAllowed);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class CheckedCoreReleaseMessage {
  CheckedCoreReleaseMessage({
    required this.releaseId,
    required this.releaseSequence,
    required this.version,
    required this.publishedAt,
    required this.coreApiMajor,
    required this.coreApiMinor,
    required this.artifactSizeBytes,
  });

  int releaseId;

  int releaseSequence;

  String version;

  String publishedAt;

  int coreApiMajor;

  int coreApiMinor;

  int artifactSizeBytes;

  List<Object?> _toList() {
    return <Object?>[
      releaseId,
      releaseSequence,
      version,
      publishedAt,
      coreApiMajor,
      coreApiMinor,
      artifactSizeBytes,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CheckedCoreReleaseMessage decode(Object result) {
    result as List<Object?>;
    return CheckedCoreReleaseMessage(
      releaseId: result[0]! as int,
      releaseSequence: result[1]! as int,
      version: result[2]! as String,
      publishedAt: result[3]! as String,
      coreApiMajor: result[4]! as int,
      coreApiMinor: result[5]! as int,
      artifactSizeBytes: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CheckedCoreReleaseMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(releaseId, other.releaseId) &&
        _deepEquals(releaseSequence, other.releaseSequence) &&
        _deepEquals(version, other.version) &&
        _deepEquals(publishedAt, other.publishedAt) &&
        _deepEquals(coreApiMajor, other.coreApiMajor) &&
        _deepEquals(coreApiMinor, other.coreApiMinor) &&
        _deepEquals(artifactSizeBytes, other.artifactSizeBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class CoreCandidateProbeMessage {
  CoreCandidateProbeMessage({
    required this.healthy,
    required this.candidate,
    required this.validatedFixtureCount,
    this.errorCode,
  });

  bool healthy;

  CoreBundleSlotMessage candidate;

  int validatedFixtureCount;

  String? errorCode;

  List<Object?> _toList() {
    return <Object?>[healthy, candidate, validatedFixtureCount, errorCode];
  }

  Object encode() {
    return _toList();
  }

  static CoreCandidateProbeMessage decode(Object result) {
    result as List<Object?>;
    return CoreCandidateProbeMessage(
      healthy: result[0]! as bool,
      candidate: result[1]! as CoreBundleSlotMessage,
      validatedFixtureCount: result[2]! as int,
      errorCode: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CoreCandidateProbeMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(healthy, other.healthy) &&
        _deepEquals(candidate, other.candidate) &&
        _deepEquals(validatedFixtureCount, other.validatedFixtureCount) &&
        _deepEquals(errorCode, other.errorCode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is RuntimeFlagsMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is NetworkInterfaceStateMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is UrlTestRequestMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PreconnectUrlTestRequestMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PreconnectUrlTestResultMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is CoreBundleSlotMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is CoreManagerStateMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is CheckedCoreReleaseMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is CoreCandidateProbeMessage) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return RuntimeFlagsMessage.decode(readValue(buffer)!);
      case 130:
        return NetworkInterfaceStateMessage.decode(readValue(buffer)!);
      case 131:
        return UrlTestRequestMessage.decode(readValue(buffer)!);
      case 132:
        return PreconnectUrlTestRequestMessage.decode(readValue(buffer)!);
      case 133:
        return PreconnectUrlTestResultMessage.decode(readValue(buffer)!);
      case 134:
        return CoreBundleSlotMessage.decode(readValue(buffer)!);
      case 135:
        return CoreManagerStateMessage.decode(readValue(buffer)!);
      case 136:
        return CheckedCoreReleaseMessage.decode(readValue(buffer)!);
      case 137:
        return CoreCandidateProbeMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CoreManagerHostApi {
  /// Constructor for [CoreManagerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CoreManagerHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CoreManagerStateMessage> getState() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.CoreManagerHostApi.getState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CoreManagerStateMessage;
  }

  Future<CheckedCoreReleaseMessage> checkLatest() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.CoreManagerHostApi.checkLatest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CheckedCoreReleaseMessage;
  }

  Future<CoreBundleSlotMessage> downloadChecked() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.CoreManagerHostApi.downloadChecked$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CoreBundleSlotMessage;
  }

  Future<CoreCandidateProbeMessage> probeCandidate() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.CoreManagerHostApi.probeCandidate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CoreCandidateProbeMessage;
  }

  Future<CoreManagerStateMessage> activateCandidate() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.CoreManagerHostApi.activateCandidate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CoreManagerStateMessage;
  }

  Future<CoreManagerStateMessage> rollback() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.CoreManagerHostApi.rollback$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CoreManagerStateMessage;
  }
}

class SingboxHostApi {
  /// Constructor for [SingboxHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SingboxHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> prepareVpn(bool requiresVpn) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.prepareVpn$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[requiresVpn],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<Map<String?, Object?>> vpnPermissionStatus() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.vpnPermissionStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String?, Object?>();
  }

  Future<void> start(String config, bool useVpn) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[config, useVpn],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> startPrepared(bool useVpn) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.startPrepared$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[useVpn],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> applyConfig(String config, bool useVpn, bool restartCore) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.applyConfig$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[config, useVpn, restartCore],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> applyPreparedConfig(bool useVpn, bool restartCore) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.applyPreparedConfig$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[useVpn, restartCore],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String> getConfigPath() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getConfigPath$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<Map<String?, Object?>> getRuntimeFlags() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getRuntimeFlags$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String?, Object?>();
  }

  Future<void> setRuntimeFlags(RuntimeFlagsMessage flags) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.setRuntimeFlags$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[flags],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> reload() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.reload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stop(String reason) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[reason],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> selectOutbound(String groupTag, String outboundTag) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.selectOutbound$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[groupTag, outboundTag],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> addOutbound(String selectorTag, String outboundJson) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.addOutbound$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[selectorTag, outboundJson],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> removeOutbound(String selectorTag, String outboundTag) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.removeOutbound$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[selectorTag, outboundTag],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> urlTest(UrlTestRequestMessage request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.urlTest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<Map<String?, Object?>> startManagedUrlTest(
    UrlTestRequestMessage request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.startManagedUrlTest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String?, Object?>();
  }

  Future<Map<String?, Object?>> getManagedUrlTestSession(
    String sessionId,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getManagedUrlTestSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String?, Object?>();
  }

  Future<Map<String?, Object?>> cancelManagedUrlTest(String sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.cancelManagedUrlTest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String?, Object?>();
  }

  Future<Map<String?, Object?>> getRuntimeSnapshot() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getRuntimeSnapshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String?, Object?>();
  }

  Future<PreconnectUrlTestResultMessage> preconnectUrlTest(
    PreconnectUrlTestRequestMessage request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.preconnectUrlTest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PreconnectUrlTestResultMessage;
  }

  Future<void> cancelPreconnectUrlTest() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.cancelPreconnectUrlTest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> removeUrlTestOutbounds(
    String groupTag,
    List<String?> outboundTags,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.removeUrlTestOutbounds$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[groupTag, outboundTags],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<Map<String?, Object?>> status() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.status$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String?, Object?>();
  }

  Future<Map<String?, Object?>> lookupOutboundExternalInfo(
    String outboundTag,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.lookupOutboundExternalInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[outboundTag],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String?, Object?>();
  }

  Future<NetworkInterfaceStateMessage> getNetworkInterfaceState() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getNetworkInterfaceState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NetworkInterfaceStateMessage;
  }

  Future<String?> exportLogs(String content, String suggestedName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.exportLogs$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[content, suggestedName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<String> getAndroidId() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getAndroidId$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> getHydraDeviceId(String canonicalOrigin) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getHydraDeviceId$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[canonicalOrigin],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<Map<String?, Object?>> getSubscriptionRequestDeviceInfo() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getSubscriptionRequestDeviceInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String?, Object?>();
  }

  Future<Map<String?, Object?>> getPlatformDeviceInfo() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getPlatformDeviceInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String?, Object?>();
  }

  Future<Map<String?, Object?>> getAppVersionInfo() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getAppVersionInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String?, Object?>();
  }

  Future<String> getCoreVersion() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getCoreVersion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> getCoreCapabilities() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getCoreCapabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> getHydraCoreBuildInfo() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getHydraCoreBuildInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> validateHydraConfig(String content, String profile) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.validateHydraConfig$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[content, profile],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> validateHydraSubscription(String content) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.validateHydraSubscription$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[content],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> inspectHydraSubscription(String content) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.inspectHydraSubscription$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[content],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> openHydraSubscriptionJwe(
    String envelope,
    String keyBase64Url,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.openHydraSubscriptionJwe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[envelope, keyBase64Url],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> validateHydraSubscriptionJwe(
    String envelope,
    String keyBase64Url,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.validateHydraSubscriptionJwe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[envelope, keyBase64Url],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> inspectHydraSubscriptionJwe(
    String envelope,
    String keyBase64Url,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.inspectHydraSubscriptionJwe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[envelope, keyBase64Url],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<void> checkConfig(String config) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.checkConfig$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[config],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<Map<String?, Object?>> getPerformanceSnapshot() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getPerformanceSnapshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String?, Object?>();
  }

  Future<Map<String?, Object?>> getHappCrypt5Support() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getHappCrypt5Support$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as Map<Object?, Object?>)
        .cast<String?, Object?>();
  }

  Future<List<Map<String?, Object?>?>> getInstalledApps() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.getInstalledApps$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<Map<String?, Object?>?>();
  }

  Future<void> setQuickSettingsTileLabel(String label) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hydrabox.SingboxHostApi.setQuickSettingsTileLabel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[label],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
